name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * 0'

env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Login to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push '${{ github.repository_owner }}/openvpn:latest'
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Dockerfile
          context: .
          tags: ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/openvpn:latest
          pull: true

      - name: Build and push '${{ github.repository_owner }}/openvpn:latest-aarch64'
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Dockerfile.aarch64
          context: .
          tags: ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/openvpn:latest-aarch64
          pull: true
          platforms: linux/arm64